# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OboardCamDisp.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 440)
        MainWindow.setFixedSize(1000, 440)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setAcceptDrops(True)
        MainWindow.setToolTipDuration(0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setAcceptDrops(True)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setAcceptDrops(True)
        self.frame_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.FileCkb = QtWidgets.QCheckBox(self.frame_2)
        self.FileCkb.setGeometry(QtCore.QRect(100, 350, 90, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.FileCkb.setFont(font)
        self.FileCkb.setObjectName("FileCkb")
        self.GoBtn = QtWidgets.QPushButton(self.frame_2)
        self.GoBtn.setGeometry(QtCore.QRect(5, 290, 80, 80))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.GoBtn.setFont(font)
        self.GoBtn.setObjectName("GoBtn")
        self.InfoTE = QtWidgets.QTextEdit(self.frame_2)
        self.InfoTE.setGeometry(QtCore.QRect(5, 40, 950, 240))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(7)
        self.InfoTE.setFont(font)
        self.InfoTE.setDocumentTitle("")
        self.InfoTE.setReadOnly(True)
        self.InfoTE.setObjectName("InfoTE")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(890, 360, 60, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.NewPathLE = QtWidgets.QLineEdit(self.frame_2)
        self.NewPathLE.setGeometry(QtCore.QRect(480, 5, 400, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.NewPathLE.setFont(font)
        self.NewPathLE.setText("")
        self.NewPathLE.setObjectName("NewPathLE")
        self.IgnoreCkb = QtWidgets.QCheckBox(self.frame_2)
        self.IgnoreCkb.setGeometry(QtCore.QRect(100, 290, 90, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.IgnoreCkb.setFont(font)
        self.IgnoreCkb.setObjectName("IgnoreCkb")
        self.OneBtn = QtWidgets.QPushButton(self.frame_2)
        self.OneBtn.setGeometry(QtCore.QRect(420, 300, 70, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.OneBtn.setFont(font)
        self.OneBtn.setObjectName("OneBtn")
        self.TimeCostLCD = QtWidgets.QLCDNumber(self.frame_2)
        self.TimeCostLCD.setGeometry(QtCore.QRect(880, 290, 70, 30))
        self.TimeCostLCD.setObjectName("TimeCostLCD")
        self.ChoiceSld = QtWidgets.QSlider(self.frame_2)
        self.ChoiceSld.setGeometry(QtCore.QRect(500, 302, 50, 20))
        self.ChoiceSld.setMaximum(1)
        self.ChoiceSld.setProperty("value", 1)
        self.ChoiceSld.setOrientation(QtCore.Qt.Horizontal)
        self.ChoiceSld.setObjectName("ChoiceSld")
        self.SimpleBtn = QtWidgets.QPushButton(self.frame_2)
        self.SimpleBtn.setGeometry(QtCore.QRect(420, 340, 70, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SimpleBtn.setFont(font)
        self.SimpleBtn.setObjectName("SimpleBtn")
        self.ForceCkb = QtWidgets.QCheckBox(self.frame_2)
        self.ForceCkb.setGeometry(QtCore.QRect(100, 320, 110, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ForceCkb.setFont(font)
        self.ForceCkb.setObjectName("ForceCkb")
        self.OriginPathLE = QtWidgets.QLineEdit(self.frame_2)
        self.OriginPathLE.setGeometry(QtCore.QRect(5, 5, 380, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.OriginPathLE.setFont(font)
        self.OriginPathLE.setAcceptDrops(True)
        self.OriginPathLE.setText("")
        self.OriginPathLE.setObjectName("OriginPathLE")
        self.ChoiceSld_2 = QtWidgets.QSlider(self.frame_2)
        self.ChoiceSld_2.setGeometry(QtCore.QRect(500, 342, 50, 20))
        self.ChoiceSld_2.setMaximum(1)
        self.ChoiceSld_2.setOrientation(QtCore.Qt.Horizontal)
        self.ChoiceSld_2.setObjectName("ChoiceSld_2")
        self.DiffBtn = QtWidgets.QPushButton(self.frame_2)
        self.DiffBtn.setGeometry(QtCore.QRect(560, 300, 70, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DiffBtn.setFont(font)
        self.DiffBtn.setObjectName("DiffBtn")
        self.ComplexBtn = QtWidgets.QPushButton(self.frame_2)
        self.ComplexBtn.setGeometry(QtCore.QRect(560, 340, 70, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ComplexBtn.setFont(font)
        self.ComplexBtn.setObjectName("ComplexBtn")
        self.OriginPathBtn = QtWidgets.QPushButton(self.frame_2)
        self.OriginPathBtn.setGeometry(QtCore.QRect(385, 5, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.OriginPathBtn.setFont(font)
        self.OriginPathBtn.setObjectName("OriginPathBtn")
        self.NewPathBtn = QtWidgets.QPushButton(self.frame_2)
        self.NewPathBtn.setGeometry(QtCore.QRect(880, 5, 75, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.NewPathBtn.setFont(font)
        self.NewPathBtn.setObjectName("NewPathBtn")
        self.IniBtn = QtWidgets.QPushButton(self.frame_2)
        self.IniBtn.setGeometry(QtCore.QRect(850, 357, 30, 20))
        self.IniBtn.setObjectName("IniBtn")
        self.gridLayout_2.addWidget(self.frame_2, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("myicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DIFFCODE                     by Rookie"))
        self.FileCkb.setText(_translate("MainWindow", "SaveAsTXT"))
        self.GoBtn.setText(_translate("MainWindow", "GO"))
        self.label.setText(_translate("MainWindow", "By Rookie"))
        self.IgnoreCkb.setText(_translate("MainWindow", "IgnoreCase"))
        self.OneBtn.setText(_translate("MainWindow", "ONE"))
        self.SimpleBtn.setText(_translate("MainWindow", "SIMPLE"))
        self.ForceCkb.setText(_translate("MainWindow", "ForceParseALL"))
        self.DiffBtn.setText(_translate("MainWindow", "DIFF"))
        self.ComplexBtn.setText(_translate("MainWindow", "COMPLEX"))
        self.OriginPathBtn.setText(_translate("MainWindow", "OriginPath"))
        self.NewPathBtn.setText(_translate("MainWindow", "NewPath"))
        self.IniBtn.setText(_translate("MainWindow", "INI"))
