# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OboardCamDisp.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(261, 189)
        MainWindow.setFixedSize(261, 189)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setAcceptDrops(True)
        MainWindow.setToolTipDuration(0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setAcceptDrops(True)
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setAcceptDrops(True)
        self.frame_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.GoBtn = QtWidgets.QPushButton(self.frame_2)
        self.GoBtn.setGeometry(QtCore.QRect(0, 80, 170, 45))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.GoBtn.setFont(font)
        self.GoBtn.setText("")
        self.GoBtn.setObjectName("GoBtn")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(180, 110, 60, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.TimeCostLCD = QtWidgets.QLCDNumber(self.frame_2)
        self.TimeCostLCD.setGeometry(QtCore.QRect(170, 80, 70, 30))
        self.TimeCostLCD.setObjectName("TimeCostLCD")
        self.leftTE = QtWidgets.QTextEdit(self.frame_2)
        self.leftTE.setGeometry(QtCore.QRect(0, 0, 120, 80))
        self.leftTE.setMouseTracking(True)
        self.leftTE.setObjectName("leftTE")
        self.rightTE = QtWidgets.QTextEdit(self.frame_2)
        self.rightTE.setGeometry(QtCore.QRect(120, 0, 120, 80))
        self.rightTE.setMouseTracking(True)
        self.rightTE.setObjectName("rightTE")
        self.line = QtWidgets.QFrame(self.frame_2)
        self.line.setGeometry(QtCore.QRect(110, 0, 20, 79))
        self.line.setMinimumSize(QtCore.QSize(20, 0))
        self.line.setSizeIncrement(QtCore.QSize(20, 0))
        self.line.setBaseSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.line.setFont(font)
        self.line.setLineWidth(0)
        self.line.setMidLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.frame_2, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 261, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuSettings_2 = QtWidgets.QMenu(self.menuBar)
        self.menuSettings_2.setObjectName("menuSettings_2")
        MainWindow.setMenuBar(self.menuBar)
        self.OneMB = QtWidgets.QAction(MainWindow)
        self.OneMB.setCheckable(True)
        self.OneMB.setChecked(False)
        self.OneMB.setObjectName("OneMB")
        self.DiffMB = QtWidgets.QAction(MainWindow)
        self.DiffMB.setCheckable(True)
        self.DiffMB.setChecked(True)
        self.DiffMB.setObjectName("DiffMB")
        self.SimpleMB = QtWidgets.QAction(MainWindow)
        self.SimpleMB.setCheckable(True)
        self.SimpleMB.setChecked(True)
        self.SimpleMB.setObjectName("SimpleMB")
        self.ComplexMB = QtWidgets.QAction(MainWindow)
        self.ComplexMB.setCheckable(True)
        self.ComplexMB.setObjectName("ComplexMB")
        self.IgnoreMB = QtWidgets.QAction(MainWindow)
        self.IgnoreMB.setCheckable(True)
        self.IgnoreMB.setObjectName("IgnoreMB")
        self.ForceMB = QtWidgets.QAction(MainWindow)
        self.ForceMB.setCheckable(True)
        self.ForceMB.setObjectName("ForceMB")
        self.FileMB = QtWidgets.QAction(MainWindow)
        self.FileMB.setCheckable(True)
        self.FileMB.setObjectName("FileMB")
        self.menuSettings.addAction(self.OneMB)
        self.menuSettings.addAction(self.DiffMB)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.SimpleMB)
        self.menuSettings.addAction(self.ComplexMB)
        self.menuSettings_2.addAction(self.IgnoreMB)
        self.menuSettings_2.addAction(self.ForceMB)
        self.menuSettings_2.addAction(self.FileMB)
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menuSettings_2.menuAction())
        self.setStyleSheet("QTextEdit{background:#000000;color:#DDDDDD}"
                           "QPushButton{background:#00FF00}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("myicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DIFFCODE                     by Rookie"))
        self.label.setText(_translate("MainWindow", "By Rookie"))
        self.menuSettings.setTitle(_translate("MainWindow", "Models"))
        self.menuSettings_2.setTitle(_translate("MainWindow", "Settings"))
        self.OneMB.setText(_translate("MainWindow", "Counting One File"))
        self.DiffMB.setText(_translate("MainWindow", "DiffCounting Two Files"))
        self.SimpleMB.setText(_translate("MainWindow", "Simple Output"))
        self.ComplexMB.setText(_translate("MainWindow", "Complex Output"))
        self.IgnoreMB.setText(_translate("MainWindow", "IgnoreCase"))
        self.ForceMB.setText(_translate("MainWindow", "ForceParseALL"))
        self.FileMB.setText(_translate("MainWindow", "SaveToTxt"))
